// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_PROJECT_REF = (() => {
  try {
    return new URL(SUPABASE_URL).hostname.split(".")[0] ?? "";
  } catch {
    return "";
  }
})();
const SUPABASE_STORAGE_KEY = `sb-${SUPABASE_PROJECT_REF}-auth-token`;

const RETRYABLE_STATUS_CODES = new Set([502, 503, 504]);

const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const isAbortOrNetworkError = (error: unknown) => {
  if (error instanceof DOMException && error.name === "AbortError") return true;
  const message = error instanceof Error ? error.message : String(error ?? "");
  return /aborted|abort|networkerror|failed to fetch|ERR_ABORTED/i.test(message);
};

const createRequestInitForRetry = async (
  input: RequestInfo | URL,
  init: RequestInit | undefined,
  ignoreSignal: boolean,
): Promise<{ requestInput: RequestInfo | URL; requestInit: RequestInit | undefined }> => {
  if (!ignoreSignal) {
    return { requestInput: input, requestInit: init };
  }

  const initWithoutSignal = (() => {
    if (!init) return undefined;
    const { signal: _signal, ...rest } = init;
    return rest;
  })();

  if (input instanceof Request) {
    const method = initWithoutSignal?.method ?? input.method;
    const headers = initWithoutSignal?.headers ?? input.headers;
    const bodyFromInit = initWithoutSignal?.body;

    let body: BodyInit | undefined = bodyFromInit;
    if (!body && method !== "GET" && method !== "HEAD") {
      const clonedRequest = input.clone();
      const payload = await clonedRequest.arrayBuffer();
      if (payload.byteLength > 0) {
        body = payload;
      }
    }

    return {
      requestInput: input.url,
      requestInit: {
        ...initWithoutSignal,
        method,
        headers,
        body,
      },
    };
  }

  return {
    requestInput: input,
    requestInit: initWithoutSignal,
  };
};

const fetchWithAuthRetry: typeof fetch = async (input, init) => {
  const requestUrl = typeof input === "string"
    ? input
    : input instanceof URL
      ? input.toString()
      : input.url;

  const isAuthTokenRequest = requestUrl.includes("/auth/v1/token");
  // More aggressive retries for token endpoints (handles refresh_token and password grants)
  const maxAttempts = isAuthTokenRequest ? 5 : 1;

  let lastError: unknown;
  let lastResponse: Response | null = null;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const { requestInput, requestInit } = await createRequestInitForRetry(input, init, isAuthTokenRequest);
      const response = await fetch(requestInput, requestInit);
      lastResponse = response;

      // Return successful responses or non-retryable errors immediately
      if (!isAuthTokenRequest || !RETRYABLE_STATUS_CODES.has(response.status) || attempt === maxAttempts) {
        return response;
      }
      
      // Clone the response before the next iteration to prevent reading body twice
      response.body?.cancel?.();
    } catch (error) {
      lastError = error;
      const canRetryThrownError = isAuthTokenRequest && isAbortOrNetworkError(error);

      if ((!isAuthTokenRequest && !canRetryThrownError) || attempt === maxAttempts) {
        throw error;
      }
    }

    // Exponential backoff with jitter: 500ms, 1s, 2s, 4s for attempts 1-4
    const baseDelay = Math.pow(2, attempt - 1) * 500;
    const jitter = Math.random() * 200; // 0-200ms jitter
    await wait(baseDelay + jitter);
  }

  // Return the last 504 response rather than throwing, let Supabase client handle it
  if (lastResponse && RETRYABLE_STATUS_CODES.has(lastResponse.status)) {
    return lastResponse;
  }

  throw lastError instanceof Error ? lastError : new Error("Auth request failed");
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithAuthRetry,
  },
  auth: {
    storage: localStorage,
    storageKey: SUPABASE_STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
  }
});

const isInvalidRefreshTokenError = (error: unknown) => {
  const message = error instanceof Error ? error.message : String(error ?? "");
  return /Invalid Refresh Token|Refresh Token Not Found|JWT expired|invalid_grant/i.test(message);
};

const clearSupabaseAuthStorage = () => {
  const keysToRemove: string[] = [];

  for (let index = 0; index < localStorage.length; index += 1) {
    const key = localStorage.key(index);
    if (!key) continue;

    const isSupabaseAuthKey = key.startsWith("sb-") && key.endsWith("-auth-token");
    if (isSupabaseAuthKey) {
      keysToRemove.push(key);
    }
  }

  if (!keysToRemove.includes(SUPABASE_STORAGE_KEY)) {
    keysToRemove.push(SUPABASE_STORAGE_KEY);
  }

  keysToRemove.forEach((key) => localStorage.removeItem(key));
};

export const recoverFromInvalidRefreshToken = async (error: unknown) => {
  if (!isInvalidRefreshTokenError(error)) return false;

  clearSupabaseAuthStorage();

  try {
    await supabase.auth.signOut({ scope: "local" });
  } catch {
    // ignore - storage has already been cleared
  }

  return true;
};